config/routes.rb
Rails.application.routes.draw do
  resources :atweets, only: [:index, :new, :create, :edit, :update, :destroy]do
    collection do
      post :confirm
    end
  end

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  root 'top#index'
  

end

app/models/atweet.rb
class Atweet < ActiveRecord::Base
  validates :content, presence: true
   validates_length_of :content, :maximum => 140
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/atweets_controller.rb
class AtweetsController < ApplicationController
  before_action :set_atweet, only: [:edit, :update, :destroy]
  def index
    @atweet = Atweet.all
  end

  def new
    if params[:back]
      @atweet = Atweet.new(atweet_params)
    else
      @atweet = Atweet.new
    end
  end

  def create
    @atweet = Atweet.create(atweet_params)
    if @atweet.save
      redirect_to atweets_path, notice: "つぃーとしました！"
    else
      render 'new'
    end
  end

  def edit
    @atweet = Atweet.find(params[:id])
  end

  def update
    @atweet = Atweet.find(params[:id])
    @atweet.update(atweet_params)
    redirect_to atweets_path, notice: "つぃーとを更新しました！"
  end

  def destroy
    @atweet = Atweet.find(params[:id])
    @atweet.destroy
    redirect_to atweets_path, notice: "つぃーとを削除しました！"
  end

  def confirm
    @atweet = Atweet.new(atweet_params)
    render :new if @atweet.invalid?
  end

  private
    def atweet_params
      params.require(:atweet).permit(:content)
    end

    def set_atweet
      @atweet = Atweet.find(params[:id])
    end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atweets_helper.rb
module AtweetsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_atweets_path
    elsif action_name == 'edit'
      atweet_path
    end
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/atweets/_form.html.erb
<%= form_for(@atweet, url: choose_new_or_edit) do |f| %>
  <% if @atweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= @atweet.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @atweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :content %>
  <%= f.text_field :content, class: 'form-control' %>
  <br>
  <%= f.submit %>
<% end %>

<%= link_to "つぃーと一覧画面にもどる", atweets_path %>

app/views/atweets/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

<h3>以下の内容で、送信する。</h3>

<%= form_for(@atweet) do |f| %>
  <%= f.hidden_field :content %>

  <p>本文:<%= @atweet.content %></p>
  <%= f.submit "投稿する",class: 'btn btn-primary btn-block' %>
<% end %>

<%= form_for(@atweet, url: new_atweet_path, method: 'get') do |f| %>
  <%= f.hidden_field :content %>
  <%= f.submit "もどる", name: 'back', class: 'btn btn-default btn-block' %>
<% end %>
  </div>
</div>

app/views/atweets/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
　　<h2>つぃーとを修正する</h2>
　　<%= render 'form' %>
  </div>
</div>

app/views/atweets/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">

<p><%= notice %></p>

<h1>つぃーと一覧</h1>

<% @atweet.each do |atweet| %>
  <div class="row">
  <p><%= atweet.content %></p>
  <%= link_to "編集", edit_atweet_path(atweet.id), class: 'btn btn-default btn-sm btn-success' %>
  <%= link_to "削除", atweet_path(atweet.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
    </div>
    <% end %>

<%= link_to "つぃーとする", new_atweet_path, class: 'btn btn-default' %>

  </div>
</div>

app/views/atweets/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
　　<h2>つぃーとする</h2>
　　<%= render 'form' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitte</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <ul>
  <li><%= link_to "トップページ", root_path %></li>
  <li><%= link_to "Twitte", atweets_path %></li>
  </ul>
</header>

<%= yield %>

</body>
</html>

app/views/top/index.html.erb
<!DOCTYPE html>
<html lang="ja" data-scribe-reduced-action-queue="true">
<section class="main-header">
  <img src="<%= asset_path "twiite.png" %>">
</section>
<div id="page-top-btn" class="page-top-btn">
    <p><a class="move-page-top" id="move-page-top">▲</a></p>
</div>
 <section class="function container-fluid">
    <div class="row">
    <h2>Function</h2>
  <div class="function-images">
  <div class="col-md-3 col-sm-6">
  <div class="function-image">
   <img src="<%= asset_path "key.png" %>">
   <p>ログイン機能</p>
  </div>
        </div>
  <div class="col-md-3 col-sm-6">
        <div class="function-image">
   <img src="<%= asset_path "mails.png" %>">
   <p>メール送信機能</p>
        </div>
        </div>
  <div class="col-md-3 col-sm-6">
        <div class="function-image">
   <img src="<%= asset_path "girls.png" %>">
   <p>友達つながり機能</p>
        </div>
        </div>
  <div class="col-md-3 col-sm-6">
        <div class="function-image">
   <img src="<%= asset_path "comment.png" %>">
   <p>コメント投稿機能</p>
        </div>
        </div>
    </div>
    </div>
  </section>

</html>